version: "3"
services:
  # server:
  #   container_name: cpe-guesser
  #   image: "harry/cpe-guesser"
  #   build: ..
  #   volumes:
  #     - ../data/:/data/:rw
  #     - ./settings.yaml:/app/config/settings.yaml
  #   environment:
  #     - server_port= 8080
  #     - client_host= 127.0.0.1
  #     - client_port= 3000
  #     - redis_host= 127.0.0.1
  #     - redis_port= 6379
  #     - cpe_path= '/home/blackharry/Documents/NXO-Rennes/NXO-CPE-guesser/data/official-cpe-dictionary_v2.3.xml'
  #     - cpe_source= 'https://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz'
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - redis
  redis:
    container_name: cpe-guesser-db
    image: "redis:alpine"
    ports:
      - 6379:6379